
# Package-introduced administrative user
[admins]
admin = 

[couchdb]
uuid = 87c53fbac1ff1193492c5ec98b27aae9

[chttpd_auth]
secret = ${COUCHDB_SECRET}
authentication_handlers = {chttpd_auth, cookie_authentication_handler}, {couch_httpd_auth, proxy_authentication_handler}, {chttpd_auth, default_authentication_handler}
x_auth_username = X-Auth-CouchDB-UserName
x_auth_roles = X-Auth-CouchDB-Roles
x_auth_token = X-Auth-CouchDB-Token
proxy_use_secret = false

[couch_httpd_auth]
secret = ${COUCHDB_SECRET}

[cors]
headers = accept, authorization, content-type, origin, referer
methods = GET, PUT, POST, HEAD, DELETE
origins = *
credentials = true

[chttpd]
enable_cors = false
port = 5984
bind_address = 127.0.0.1
authentication_handlers = {chttpd_auth, cookie_authentication_handler}, {chttpd_auth, proxy_authentication_handler}, {chttpd_auth, default_authentication_handler}
